# Generated by Django 5.1.2 on 2025-12-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_desc', models.CharField(max_length=120)),
                ('parking_spot', models.CharField(blank=True, max_length=30)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-arrived_at',),
            },
        ),
        migrations.CreateModel(
            name='PickupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_orders', models.PositiveIntegerField(default=5)),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
    ]
